### ISSUE TITLE
Tool to use all features of the R.A.T.7 (e.g. setting the dpi axis value for the different modes)

### ISSUE THREAD

**Issue by xwavex** [cquaid/RAT_driver#1]
Hi cquaid,
I got very inspired by your driver for one of the best input devices ever - good work!
Lately I reverse engineered the communication of the RAT. With my tool it is now possible e.g. to adjust the DPI settings for each mode on linux. So if your are still using your RAT, this might be interesting for you: https://github.com/xwavex/pyRAT

Perhaps you could include those features into your driver. That would be awesome!

Cheers,
XWaVeX

**Comment by cquaid** [comment]
Cool, I'll take a look at it on Monday.  I've been out of town for a bit.  I'd love to add the DPI changing feature.

**Comment by cquaid** [comment]
Sorry it took so long, but this should be complete now.  Great write-up on pyRAT by the way.  I need to do something like that for this.

Switched to libusb 1.0 (still synchronous until I decide to support multiple RAT devices from the same driver).

Added the DPI get CTRL commands
Added the DPI set CTRL commands

I guess the next step is to figure out what's up with the snipe button.  It's DPI change is dependent on the current profile.  I think it's software controlled.  Unsure though.
